// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('EvolutionApp').controller('EvolutionCtrl', function($scope, utils, io) {
    $scope.phase = "Evolution";
    $scope.deck = {
      number: 40
    };
    $scope.players = [
      {
        name: 'Edouard',
        hand: [
          {
            shortName: "intellect"
          }, {
            shortName: "carnivorous"
          }, {
            shortName: "vivaporous"
          }, {
            shortName: "tailLoss"
          }
        ],
        species: [
          [], [
            {
              name: "intellect",
              shortName: "intellect"
            }, {
              name: "carnivorous",
              cost: 1,
              shortName: "intellect"
            }
          ]
        ]
      }, {
        name: 'Jacob',
        cardNumber: 5,
        species: [
          [], [
            {
              name: "tailLoss",
              shortName: "tailLoss"
            }, {
              name: "vivaporous",
              cost: 1,
              shortName: "vivaporous"
            }
          ]
        ]
      }, {
        name: 'Charlotte',
        cardNumber: 2,
        species: [
          [], [
            {
              name: "tailLoss",
              shortName: "tailLoss"
            }
          ]
        ]
      }
    ];
    $scope.player = function() {
      return $scope.players[0];
    };
    $scope.end = function(card, specie) {
      console.log("next player");
      return socket.emit('end turn', {
        card: card,
        specie: specie
      });
    };
    $scope.selectedCard = function() {
      var card, _i, _len, _ref;
      _ref = $scope.player().hand;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        card = _ref[_i];
        if (card.selected) {
          return card;
        }
      }
    };
    $scope.selectCard = function(card) {
      var _ref;
      if ((_ref = $scope.selectedCard()) != null) {
        _ref.selected = false;
      }
      card.selected = true;
      return $scope.checkCompatible(card);
    };
    $scope.checkCompatible = function(card) {
      var specie, _i, _len, _ref, _results;
      _ref = $scope.player().species;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        specie = _ref[_i];
        specie.compatible = false;
        _results.push(specie.compatible = true);
      }
      return _results;
    };
    return $scope.selectSpecie = function(specie) {
      var card;
      if (specie.compatible) {
        card = $scope.selectedCard();
        $scope.player().hand.remove(card);
        specie.push(card);
        return $scope.end(card, specie);
      }
    };
  });

}).call(this);

//# sourceMappingURL=evolution.map
