// Generated by CoffeeScript 1.7.1
(function() {
  angular.module("IoService", []).service("io", function() {
    return this.io = io("http://192.168.1.84:3000/");
  });

}).call(this);

//# sourceMappingURL=ioService.map
